export { Btn } from "@/components/design/Btn";
export { Chip } from "@/components/design/Chip";
export { Marquee } from "@/components/design/Marquee";
export { GridBg } from "@/components/design/GridBg";
export { Reveal } from "@/components/design/Reveal";
export { NumberTicker } from "@/components/design/NumberTicker";
export { SectionTag } from "@/components/design/SectionTag";
export { ShimmerBtn } from "@/components/design/ShimmerBtn";
export { BeamFrame } from "@/components/design/BeamFrame";
export { Word } from "@/components/design/Word";
export { DesignNav } from "@/components/design/DesignNav";
export { DesignFooter } from "@/components/design/DesignFooter";
export { DesignLayout } from "@/components/design/DesignLayout";
export { GoogleMark, WithGoogleMark } from "@/components/design/GoogleMark";
export { SocialDock } from "@/components/design/SocialDock";
